lib/build.gradle
Hi @winsmith,
This PR cleans the release definitions so the library can be imported as a dependency like:
```
implementation 'com.github.kkostov:KotlinSDK:e592ffd5edb1f82a188b70f737ade23065abd5cc'
```
Once there are release tags in https://github.com/TelemetryDeck/KotlinSDK this can be improved to
```
implementation 'com.github.TelemetryDeck:1.0.0'
```
cf https://docs.jitpack.io/
=> Configure releases

lib/src/main/java/com/telemetrydeck/sdk/PersistentSignalCache.kt, lib/src/main/java/com/telemetrydeck/sdk/TelemetryManager.kt, lib/src/test/java/com/telemetrydeck/sdk/PersistentSignalCacheTest.kt
Hi @winsmith,
This is a (simple) implementation for persisting signals to disk so they can be sent in case of an app restart.
* When a new signal is queued, the list of pending signals is also written to disk.
* When the queue of signals is emptied, the disk cache is also purged.
=> Add a basic persistent local cache for signals

app/build.gradle, lib/build.gradle, lib/src/main/java/com/telemetrydeck/sdk/EnvironmentMetadataProvider.kt
Following on https://github.com/TelemetryDeck/KotlinSDK/issues/8, this seems to do the trick. I have not been able to test on Android API 21-23 since I don't have such a device on hand at the moment and emulators on M1 Mac don't exist before API 28 as far as I know.
=> Allow build on Android API >= 21

lib/src/main/java/com/telemetrydeck/sdk/EnvironmentMetadataProvider.kt, lib/src/test/java/com/telemetrydeck/sdk/EnvironmentMetadataProviderTest.kt
This PR changes the behaviour of the default EnvironmentMetadataProvider so that if an environment value is already set in a signal payload, it will not be overwritten.
We need this for the Flutter SDK where the flutter layer (or the user) will set some client version information.
In the iOS SDK this is known as precedence: https://github.com/TelemetryDeck/SwiftClient/blob/main/Tests/TelemetryClientTests/TelemetryClientTests.swift#L77
It will be up to every `TelemetryProvider` to implement the desired behaviour.
=> Environment provider should allow clients to set environment values

jitpack.yml, lib/build.gradle
It seems the latest version has failed to publish https://jitpack.io/#TelemetryDeck/KotlinSDK
Build log: https://jitpack.io/com/github/TelemetryDeck/KotlinSDK/2.0.0/build.log
=> Fix jitpack release

lib/src/main/java/com/telemetrydeck/sdk/Signal.kt, lib/src/main/java/com/telemetrydeck/sdk/TelemetryManager.kt, lib/src/test/java/com/telemetrydeck/sdk/TelemetryManagerTest.kt
This PR changes isTestMode to a string. 
This should address https://github.com/TelemetryDeck/FlutterSDK/issues/6
=> isTestMode should be a string in v1

lib/src/main/java/com/telemetrydeck/sdk/TelemetryManager.kt, lib/src/test/java/com/telemetrydeck/sdk/TelemetryManagerTest.kt
This PR addresses a defect where the library will ignore a custom hashing salt for the client id if one was provided.
Note: After adopting a version of the SDK including this fix, users already specifying a custom salt will see a change in the generated clientId hash which may influence some statistics.
=> Fix use of custom user salt when hashing the client id

lib/src/main/java/com/telemetrydeck/sdk/PersistentSignalCache.kt
This PR addresses #24 by making sure the directory where we write the persistent signal cache already exists.
=> Fix possible crash when the cache directory doesn't exist

README.md, lib/src/androidTest/java/com/telemetrydeck/sdk/FileUserIdentityProviderTest.kt, lib/src/main/java/com/telemetrydeck/sdk/TelemetryDeck.kt, lib/src/main/java/com/telemetrydeck/sdk/TelemetryDeckIdentityProvider.kt, lib/src/main/java/com/telemetrydeck/sdk/providers/FileUserIdentityProvider.kt, lib/src/main/java/com/telemetrydeck/sdk/providers/PlatformContextProvider.kt, lib/src/test/java/com/telemetrydeck/sdk/TelemetryDeckTests.kt
This PR fixes #14 by introducing a mechanism to automatically persist an anonymous identifier of the user's identity when none has been supplied via configuration.
=> [#14] Autogenerate user identifier

README.md, lib/src/main/java/com/telemetrydeck/sdk/providers/DefaultParameterProvider.kt, lib/src/test/java/com/telemetrydeck/sdk/TelemetryDeckTests.kt
This PR fixes #45 by making it possible to specify a map of default parameter values to be appended with outgoing signals. The feature is opt-in and can be enabled by adding our default parameter provider:
```kotlin
// create an instance of [DefaultParameterProvider] and pass the key value you wish to be appended to every signal
val provider = DefaultParameterProvider(mapOf("key" to "value"))
// add the provider when configuring an instance of TelemetryDeck
val builder = TelemetryDeck.Builder()
.appID("XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX")
.addProvider(provider)
```
=> Add a way to include default parameters with all signals

README.md, lib/src/main/java/com/telemetrydeck/sdk/SignalTransform.kt, lib/src/main/java/com/telemetrydeck/sdk/TelemetryDeck.kt, lib/src/main/java/com/telemetrydeck/sdk/TelemetryDeckProvider.kt, lib/src/main/java/com/telemetrydeck/sdk/providers/DefaultPrefixProvider.kt, lib/src/test/java/com/telemetrydeck/sdk/TelemetryDeckTests.kt, lib/src/test/java/com/telemetrydeck/sdk/providers/DefaultPrefixProviderTest.kt
This PR fixes #55 and fixes #56 by making it possible to define a default prefix for signals and/or parameters. The TelemetryDeck namespace is ignored.
The feature is opt-in and can be enabled by adding our default prefix provider:
```kotlin
val builder = TelemetryDeck.Builder()
.appID("XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX")
.addProvider(DefaultPrefixProvider("MyApp.", "MyApp.Params."))
```
With this PR, the provider interface has been extended to allow custom plugins to transform any part of a Signal and not just the additional payload.
=> Add a way to set default prefix for signals and parameters

gradle/libs.versions.toml, lib/build.gradle.kts, lib/src/androidTest/java/com/telemetrydeck/sdk/DurationSignalTrackerProviderTest.kt, lib/src/main/java/com/telemetrydeck/sdk/TelemetryDeck.kt, lib/src/main/java/com/telemetrydeck/sdk/TelemetryDeckClient.kt, lib/src/main/java/com/telemetrydeck/sdk/providers/DurationSignalTrackerProvider.kt, lib/src/main/java/com/telemetrydeck/sdk/signals/Signal.kt, lib/src/test/java/com/telemetrydeck/sdk/TelemetryDeckTests.kt
This PR fixes #51 by adding signal duration tracking. The public API is compatible with the iOS implementation (https://github.com/TelemetryDeck/SwiftSDK/pull/224):
```kotlin
TelemetryDeck.startDurationSignal("signal")
TelemetryDeck.stopAndSendDurationSignal("signal")
```
Notes:
- Duration tracking state is persisted if the app gets terminated in the background and restored on resume.
- Session duration is always provided with a precision of 3 e.g. `23.040`
=> Add signal duration tacking

README.md, gradle/libs.versions.toml, lib/build.gradle.kts, lib/src/androidTest/java/com/telemetrydeck/sdk/AccessibilityProviderFontScaleNormalTest.kt, lib/src/androidTest/java/com/telemetrydeck/sdk/AccessibilityProviderTest.kt, lib/src/androidTest/java/com/telemetrydeck/sdk/FontScaleTestRule.kt, lib/src/main/java/com/telemetrydeck/sdk/params/Accessibility.kt, lib/src/main/java/com/telemetrydeck/sdk/params/Device.kt, lib/src/main/java/com/telemetrydeck/sdk/params/UserPreference.kt, lib/src/main/java/com/telemetrydeck/sdk/providers/AccessibilityProvider.kt
Fixes #42 
The [README](https://github.com/TelemetryDeck/KotlinSDK/blob/06fee784485e5f10b9b54cb93727c871a8081871/README.md#environment-parameters) has been updated to include the list above.
@Jeehut @winsmith Please feel free to have a look. Thoughts and comments are always welcome.
=> Automatically include accessibility stats

.github/workflows/tests.yml, README.md, lib/build.gradle.kts, lib/src/main/java/com/telemetrydeck/sdk/DateSerializer.kt, lib/src/main/java/com/telemetrydeck/sdk/SignalPayload.kt, lib/src/main/java/com/telemetrydeck/sdk/TelemetryDeck.kt, lib/src/main/java/com/telemetrydeck/sdk/UUIDSerializer.kt, lib/src/main/java/com/telemetrydeck/sdk/params/Acquisition.kt, lib/src/main/java/com/telemetrydeck/sdk/providers/DurationSignalTrackerProvider.kt, lib/src/main/java/com/telemetrydeck/sdk/providers/EnvironmentParameterProvider.kt, lib/src/main/java/com/telemetrydeck/sdk/providers/PlatformContextProvider.kt, lib/src/main/java/com/telemetrydeck/sdk/providers/SessionAppProvider.kt, lib/src/main/java/com/telemetrydeck/sdk/providers/SessionTrackingSignalProvider.kt, lib/src/main/java/com/telemetrydeck/sdk/providers/helpers/ProviderDiskTools.kt, lib/src/main/java/com/telemetrydeck/sdk/signals/Acquisition.kt, lib/src/test/java/com/telemetrydeck/sdk/TelemetryDeckTests.kt
This PR fixes #52 by introducing a mechanism for tracking the first device installation. 
* The session cutoff of 90 days was carried over [from the SwiftSDK](https://github.com/TelemetryDeck/SwiftSDK/pull/230/files#diff-d964ee4356bcf74d21105bc76e8633ddfdd0453a3ab7e79e2133699c345b183cR111).
* The new tracking provider is on by default.
Note: additional averages, distinct days and other KPIs are not being submitted yet - this will come in a next release.
=> Signal when a new installation has been detected

README.md, lib/build.gradle.kts, lib/src/main/java/com/telemetrydeck/sdk/TelemetryDeck.kt, lib/src/main/java/com/telemetrydeck/sdk/providers/EnvironmentParameterProvider.kt
This PR addresses a situation where providers may attempt to send signals before TelemetryDeck is ready to do so. This was detected in the FlutterSDK when adopting version 5.0.0.
=> Fix: Cache should be available to providers during installation

README.md, lib/src/androidTest/java/com/telemetrydeck/sdk/AccessibilityProviderTest.kt, lib/src/main/java/com/telemetrydeck/sdk/params/UserPreference.kt, lib/src/main/java/com/telemetrydeck/sdk/providers/AccessibilityProvider.kt, lib/src/main/java/com/telemetrydeck/sdk/providers/helpers/LocaleHelpers.kt
This PR fixes #60 by adding the following default parameters as part of Accessibility:
| Parameter name                                                | Provider                        | Description                                        |
|---------------------------------------------------------------|---------------------------------|----------------------------------------------------|
| `TelemetryDeck.UserPreference.region`                         | `AccessibilityProvider`         | Current device region in ISO 3166-1 alpha-2 format e.g. `GB` |
| `TelemetryDeck.UserPreference.language`                       | `AccessibilityProvider`         | Current application language in ISO 639-1 format e.g. `en`  |
| `TelemetryDeck.UserPreference.colorScheme`                    | …
=> Add additional UserPreference parameters

README.md, lib/src/main/java/com/telemetrydeck/sdk/TelemetryDeck.kt, lib/src/main/java/com/telemetrydeck/sdk/TelemetryDeckClient.kt, lib/src/main/java/com/telemetrydeck/sdk/params/Acquisition.kt, lib/src/main/java/com/telemetrydeck/sdk/signals/Acquisition.kt, lib/src/test/java/com/telemetrydeck/sdk/TelemetryDeckTests.kt
This PR addresses #72 by adding Acquisition related helpers:
```kotlin
/**
* Send a `TelemetryDeck.Acquisition.userAcquired` signal with the provided channel.
*/
fun acquiredUser(channel: String,...)
```
```kotlin
/**
* Send a `TelemetryDeck.Acquisition.leadStarted` signal with the provided leadId.
*/
fun leadStarted(leadId: String,...)
```
```kotlin
/**
* Send a `TelemetryDeck.Acquisition.leadConverted` signal with the provided leadId.
*/
fun leadConverted(leadId: String,...)
```
=> Add acquisition helper methods

lib/src/main/java/com/telemetrydeck/sdk/TelemetryApiClient.kt, lib/src/main/java/com/telemetrydeck/sdk/TelemetryApiClientFactory.kt, lib/src/main/java/com/telemetrydeck/sdk/TelemetryClient.kt, lib/src/main/java/com/telemetrydeck/sdk/TelemetryClientFactory.kt, lib/src/main/java/com/telemetrydeck/sdk/TelemetryDeck.kt, lib/src/main/java/com/telemetrydeck/sdk/TelemetryManagerConfiguration.kt, lib/src/test/java/com/telemetrydeck/sdk/SignalsUnitTest.kt
=> Add support for future namespace configuration

README.md, gradle/libs.versions.toml, lib/build.gradle.kts, lib/src/androidTest/java/com/telemetrydeck/sdk/TelemetryDeckTest.kt, lib/src/main/java/com/telemetrydeck/sdk/TelemetryDeck.kt, lib/src/main/java/com/telemetrydeck/sdk/params/Calendar.kt, lib/src/main/java/com/telemetrydeck/sdk/platform/PlatformReader.kt, lib/src/main/java/com/telemetrydeck/sdk/providers/CalendarParameterProvider.kt, lib/src/test/java/com/telemetrydeck/sdk/TelemetryDeckTests.kt
This PR addresses https://github.com/TelemetryDeck/PirateMetrics/issues/43 by adding the following default parameters for all outgoing signals:
- `TelemetryDeck.Calendar.dayOfMonth`: The day-of-month (1..31) component of the date.
- `TelemetryDeck.Calendar.dayOfWeek`: The ISO 8601 number of the given day of the week. Monday is 1, Sunday is 7.
- `TelemetryDeck.Calendar.dayOfYear`: The 1-based day-of-year component of the date.
- `TelemetryDeck.Calendar.weekOfYear`: The week number within the current year as defined by `getFirstDayOfWeek()` and `getMinimalDaysInFirstWeek()`.
- `TelemetryDeck.Calendar.isWeekend`: `true` if the day of the week is Saturday or Sunday, `false` otherwise.
- `TelemetryDeck.Calendar.monthOfYear`: The number-of-the-month (1..12) component of the date.
- …
=> Add Calendar based default parameters

README.md, lib/build.gradle.kts, lib/src/main/java/com/telemetrydeck/sdk/TelemetryDeck.kt, lib/src/main/java/com/telemetrydeck/sdk/providers/EnvironmentParameterProvider.kt, lib/src/test/java/com/telemetrydeck/sdk/TelemetryDeckTests.kt
This PR allows for the namespace to be set using the builder, so it can be exposed in use-cases where the configuration is not provided directly (e.g. the [FlutterSDK](https://github.com/TelemetryDeck/FlutterSDK/pull/38))
=> Allow setting namespace via the builder

lib/src/androidTest/java/com/telemetrydeck/sdk/DurationSignalTrackerProviderTest.kt, lib/src/androidTest/java/com/telemetrydeck/sdk/TelemetryDeckTest.kt, lib/src/main/java/com/telemetrydeck/sdk/TelemetryDeck.kt, lib/src/main/java/com/telemetrydeck/sdk/TelemetryDeckClient.kt, lib/src/main/java/com/telemetrydeck/sdk/providers/DurationSignalTrackerProvider.kt
This PR fixes #82 by adding the following features to duration signals:
- `stopAndSendDurationSignal` now allows for a `floatValue` to be provided
- `stopAndSendDurationSignal` now allows for a `customUserID` to be provided
- `startDurationSignal` now allows for `includeBackgroundTime` to be set to `true`, so that total signal duration will include background and foreground time
=> Extend duration signals

lib/src/main/java/com/telemetrydeck/sdk/ExperimentalFeature.kt, lib/src/main/java/com/telemetrydeck/sdk/TelemetryDeck.kt, lib/src/main/java/com/telemetrydeck/sdk/TelemetryDeckClient.kt
Some acquisition methods were shipped as private in the SwiftSDK with the intention of being refined in the future. Based on comments in https://github.com/TelemetryDeck/SwiftSDK/pull/230 I had incorrectly assumed they were approved.
Since they've been already shipped and documented, this PR marks them as experimental, so users are aware they may change in a future version.
=> Mark methods as experimental

README.md, lib/src/androidTest/java/com/telemetrydeck/sdk/TelemetryDeckTest.kt, lib/src/main/java/com/telemetrydeck/sdk/CurrencyConverter.kt, lib/src/main/java/com/telemetrydeck/sdk/PurchaseEvent.kt, lib/src/main/java/com/telemetrydeck/sdk/PurchaseType.kt, lib/src/main/java/com/telemetrydeck/sdk/TelemetryDeck.kt, lib/src/main/java/com/telemetrydeck/sdk/TelemetryDeckClient.kt, lib/src/main/java/com/telemetrydeck/sdk/params/Purchase.kt, lib/src/main/java/com/telemetrydeck/sdk/signals/Purchase.kt
Hi all, this PR addresses https://github.com/TelemetryDeck/PirateMetrics/issues/46 by adding a facility for reporting purchases. Since there is no billing library integration at this stage, all required information is provided by the user.
The method `TelemetryDeck.purchaseCompleted()` has been added and can be invoked in response to a user purchase.
With information from the marketplace where the user made a purchase, you can inform TelemetryDeck as follows:
```kotlin
TelemetryDeck.purchaseCompleted(
event = PurchaseEvent.PAID_PURCHASE,
countryCode = "BE",
productID = "product1",
purchaseType = PurchaseType.ONE_TIME_PURCHASE,
priceAmountMicros = 7990000,
currencyCode = "EUR",
offerID = "offer1"
)
```
Depending on the specified `PurchaseEvent`, one of the following signals will be sent:
- …
=> Purchases, Free Trials, and Trial Conversions: Faciliy methods

README.md, google-services/build.gradle.kts, google-services/src/main/kotlin/com/telemetrydeck/sdk/googleservices/TelemetryDeck.kt, gradle/libs.versions.toml, lib/build.gradle.kts, lib/src/main/java/com/telemetrydeck/sdk/TelemetryDeck.kt, lib/src/main/java/com/telemetrydeck/sdk/TelemetryDeckClient.kt, lib/src/main/java/com/telemetrydeck/sdk/providers/EnvironmentParameterProvider.kt, settings.gradle.kts
This PR addresses https://github.com/TelemetryDeck/PirateMetrics/issues/46 by adding integration with Google Play Billing to make it easier to signal the completion of a purchase based on data usually available upon completion of a purchase.
App can adopt the TelemetryDeck SDK with Google Play Services to let us determine the exact purchase parameters:
```kotlin
// `build.gradle.kts`
dependencies {
// ... other dependencies
implementation("com.telemetrydeck:kotlin-sdk-google-services:6.2.0")
}
```
ℹ️ The new package `com.telemetrydeck:kotlin-sdk-google-services` uses the same version as our base SDK dependency `com.telemetrydeck:kotlin-sdk`.
An overload of `purchaseCompleted` is now available:
```kotlin
import com.telemetrydeck.sdk.googleservices.purchaseCompleted
// ...
// function …
```
=> Purchases, Free Trials, and Trial Conversions: Google Play Billing Integration

lib/src/main/java/com/telemetrydeck/sdk/providers/SessionTrackingSignalProvider.kt
If the `start` method is called when the app is already in the foreground `handleOnForeground()` is never called. So this will force call it on those cases.
- Add lifecycle state check in register() method to handle cases where TelemetryDeck is initialized after the app process is already in the foreground
- Call handleOnForeground() immediately if process is already STARTED or RESUMED
- Fixes issue where session IDs were null and session signals were missing
- Resolves issue #91
=> Fix session tracking issues
